/*
 * This file is generated by jOOQ.
*/
package tasker.model.jooq.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import tasker.model.jooq.enums.BatchType;
import tasker.model.jooq.tables.Batch;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BatchRecord extends UpdatableRecordImpl<BatchRecord> implements Record6<UUID, BatchType, Integer, Integer, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = -435239099;

    /**
     * Setter for <code>public.batch.id</code>.
     */
    public BatchRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.batch.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.batch.type</code>.
     */
    public BatchRecord setType(BatchType value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.batch.type</code>.
     */
    public BatchType getType() {
        return (BatchType) get(1);
    }

    /**
     * Setter for <code>public.batch.remain</code>.
     */
    public BatchRecord setRemain(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.batch.remain</code>.
     */
    public Integer getRemain() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.batch.total</code>.
     */
    public BatchRecord setTotal(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.batch.total</code>.
     */
    public Integer getTotal() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.batch.created</code>.
     */
    public BatchRecord setCreated(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.batch.created</code>.
     */
    public OffsetDateTime getCreated() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.batch.modified</code>.
     */
    public BatchRecord setModified(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.batch.modified</code>.
     */
    public OffsetDateTime getModified() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UUID, BatchType, Integer, Integer, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UUID, BatchType, Integer, Integer, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return Batch.BATCH.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BatchType> field2() {
        return Batch.BATCH.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Batch.BATCH.REMAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Batch.BATCH.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field5() {
        return Batch.BATCH.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field6() {
        return Batch.BATCH.MODIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchType component2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRemain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component6() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchType value2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRemain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value5() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value6() {
        return getModified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchRecord value2(BatchType value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchRecord value3(Integer value) {
        setRemain(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchRecord value4(Integer value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchRecord value5(OffsetDateTime value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchRecord value6(OffsetDateTime value) {
        setModified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BatchRecord values(UUID value1, BatchType value2, Integer value3, Integer value4, OffsetDateTime value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BatchRecord
     */
    public BatchRecord() {
        super(Batch.BATCH);
    }

    /**
     * Create a detached, initialised BatchRecord
     */
    public BatchRecord(UUID id, BatchType type, Integer remain, Integer total, OffsetDateTime created, OffsetDateTime modified) {
        super(Batch.BATCH);

        set(0, id);
        set(1, type);
        set(2, remain);
        set(3, total);
        set(4, created);
        set(5, modified);
    }
}
