/*
 * This file is generated by jOOQ.
*/
package tasker.model.jooq;


import javax.annotation.Generated;

import tasker.model.jooq.tables.Batch;
import tasker.model.jooq.tables.SchemaVersion;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.batch</code>.
     */
    public static final Batch BATCH = tasker.model.jooq.tables.Batch.BATCH;

    /**
     * The table <code>public.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = tasker.model.jooq.tables.SchemaVersion.SCHEMA_VERSION;
}
